In [204]:
import numpy as np
from netCDF4 import Dataset
from ast import literal_eval
from pyproj import Proj, transform 
import xarray as xr
import xesmf as xe

in_proj  = Proj('+proj=sinu +R=6371007.181 +nadgrids=@null +wktext') #------ Specify input projection
out_proj = Proj(init='epsg:4326')

def extract_pixel_coordinates(ULx,Uly,LRx,LRy,shape):
    x        = np.linspace(ULx, LRx, shape[0], endpoint=False) + abs((ULx-LRx)/(2*shape[0]))
    y        = np.linspace(ULy, LRy, shape[0], endpoint=False) - abs((ULy-LRy)/(2*shape[0]))
    xx, yy   = np.meshgrid(x,y)
    plon, plat = transform(in_proj, out_proj, xx, yy)
    mlon, mlat = plon[0], np.array([i[0] for i in plat])
    plon       = plon.flatten()
    plat       = plat.flatten()
    return plon, plat, mlon, mlat

ref = Dataset('MCD43A4/121/MCD43A4.A2018121.h11v04.006.2018130034701.hdf', mode='r')

In [205]:
shape2 = (2400,2400)
nrb1              = ref.variables['Nadir_Reflectance_Band1'][:].flatten()
nrb2              = ref.variables['Nadir_Reflectance_Band2'][:].flatten()
struct            = getattr(ref, 'StructMetadata.0')
struct1           = struct[struct.find('UpperLeftPointMtrs'): struct.find('LowerRightMtrs')][19:-3]
struct2           = struct[struct.find('LowerRightMtrs')    : struct.find('Projection')    ][15:-3]
ULx, ULy          = literal_eval(struct1)
LRx, LRy          = literal_eval(struct2)

In [206]:
ref_lon,ref_lat, ref_mlon, ref_mlat  = extract_pixel_coordinates(ULx,ULy,LRx,LRy,shape2)

In [207]:
grid_in  = {'lon': ref_mlon                , 'lat': ref_mlat                }
grid_out = {'lon': np.linspace(ref_mlon[0], ref_mlon[-1], 1200, endpoint=True), 'lat': np.linspace(ref_mlat[0], ref_mlat[-1], 1200, endpoint=True)}

In [181]:
plt.scatter(ref_lon1, g)

In [78]:
ref_latx = ref_lat[(nrb1.mask==False) & (nrb2.mask==False)]
ref_lonx = ref_lon[(nrb1.mask==False) & (nrb2.mask==False)]
nrb1x    = nrb1   [(nrb1.mask==False) & (nrb2.mask==False)]
nrb2x    = nrb2   [(nrb1.mask==False) & (nrb2.mask==False)]
ref_latx.shape
ref_lonx.shape
nrb1x.shape
nrb2x.shape

(5747630,)

(5747630,)

(5747630,)

(5747630,)

In [ ]:
calipso_dfs[calipso_dfs.Xindex==-999.0] = np.nan #------- Replace missing values with nan
calipso_dfs.dropna(inplace=True) 

In [199]:
x = np.linspace(1,11,10)
y = np.linspace(11,21,10)
xx, yy = np.meshgrid(x,y)
#xx
#yy
plon, plat = transform(in_proj, out_proj, xx, yy)
#plon
#plat

In [200]:
mlon = plon[0]
mlat = np.array([i[0] for i in plat])
alpha,beta = np.meshgrid(mlon,mlat)
#alpha
#plon

In [201]:
cv = np.linspace(mlon[0], mlon[-1], 5, endpoint=True)
cw = np.linspace(mlat[0], mlat[-1], 5, endpoint=True)
gamma, delta = np.meshgrid(cv,cw)
gamma, delta

(array([[8.99320592e-06, 3.14762207e-05, 5.39592355e-05, 7.64422503e-05,
         9.89252651e-05],
        [8.99320592e-06, 3.14762207e-05, 5.39592355e-05, 7.64422503e-05,
         9.89252651e-05],
        [8.99320592e-06, 3.14762207e-05, 5.39592355e-05, 7.64422503e-05,
         9.89252651e-05],
        [8.99320592e-06, 3.14762207e-05, 5.39592355e-05, 7.64422503e-05,
         9.89252651e-05],
        [8.99320592e-06, 3.14762207e-05, 5.39592355e-05, 7.64422503e-05,
         9.89252651e-05]]),
 array([[9.89252651e-05, 9.89252651e-05, 9.89252651e-05, 9.89252651e-05,
         9.89252651e-05],
        [1.21408280e-04, 1.21408280e-04, 1.21408280e-04, 1.21408280e-04,
         1.21408280e-04],
        [1.43891295e-04, 1.43891295e-04, 1.43891295e-04, 1.43891295e-04,
         1.43891295e-04],
        [1.66374310e-04, 1.66374310e-04, 1.66374310e-04, 1.66374310e-04,
         1.66374310e-04],
        [1.88857324e-04, 1.88857324e-04, 1.88857324e-04, 1.88857324e-04,
         1.88857324e-04]]))

In [202]:
plt.scatter(plon, plat, c='r')
plt.scatter(gamma, delta, c='b')

In [153]:
%matplotlib
import matplotlib.pyplot as plt
plt.scatter(plon,plat)

Using matplotlib backend: Qt5Agg


In [154]:
plt.scatter(alpha,beta)

In [94]:
c = [(i,j) for i, j in zip(xx.flatten(),yy.flatten())]

In [119]:
extract_pixel_coordinates(1,11,11,21,(10,10))

(array([1.99674465e-05, 3.32790775e-05, 4.65907084e-05, 5.99023394e-05,
        7.32139704e-05, 8.65256014e-05, 9.98372324e-05, 1.13148863e-04,
        1.26460494e-04, 1.39772125e-04, 1.82967987e-05, 3.04946644e-05,
        4.26925302e-05, 5.48903960e-05, 6.70882618e-05, 7.92861276e-05,
        9.14839933e-05, 1.03681859e-04, 1.15879725e-04, 1.28077591e-04,
        1.70035427e-05, 2.83392379e-05, 3.96749330e-05, 5.10106282e-05,
        6.23463233e-05, 7.36820184e-05, 8.50177136e-05, 9.63534087e-05,
        1.07689104e-04, 1.19024799e-04, 1.59947304e-05, 2.66578840e-05,
        3.73210376e-05, 4.79841912e-05, 5.86473448e-05, 6.93104984e-05,
        7.99736520e-05, 9.06368056e-05, 1.01299959e-04, 1.11963113e-04,
        1.52081787e-05, 2.53469646e-05, 3.54857504e-05, 4.56245362e-05,
        5.57633221e-05, 6.59021079e-05, 7.60408937e-05, 8.61796796e-05,
        9.63184654e-05, 1.06457251e-04, 1.46012749e-05, 2.43354581e-05,
        3.40696414e-05, 4.38038247e-05, 5.35380079e-05, 6.327219

In [106]:
x        = np.linspace(1 , 10, 10, endpoint=True)# + abs((ULx-LRx)/(2*shape[0]))
y        = np.linspace(11, 20, 10, endpoint=True)# - abs((ULy-LRy)/(2*shape[0]))
xx, yy   = np.meshgrid(x,y)
#xs       = xx.flatten()
#ys       = yy.flatten()
xx
yy

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

array([[11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [17., 17., 17., 17., 17., 17., 17., 17., 17., 17.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.],
       [19., 19., 19., 19., 19., 19., 19., 19., 19., 19.],
       [20., 20., 20., 20., 20., 20., 20., 20., 20., 20.]])

In [109]:
plon, plat = transform(in_proj, out_proj, xx, yy)

In [110]:
plon

array([[8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
        4.49660296e-05, 5.39592355e-05, 6.29524415e-05, 7.19456474e-05,
        8.09388533e-05, 8.99320592e-05],
       [8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
        4.49660296e-05, 5.39592355e-05, 6.29524415e-05, 7.19456474e-05,
        8.09388533e-05, 8.99320592e-05],
       [8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
        4.49660296e-05, 5.39592355e-05, 6.29524415e-05, 7.19456474e-05,
        8.09388533e-05, 8.99320592e-05],
       [8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
        4.49660296e-05, 5.39592355e-05, 6.29524415e-05, 7.19456474e-05,
        8.09388533e-05, 8.99320592e-05],
       [8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
        4.49660296e-05, 5.39592355e-05, 6.29524415e-05, 7.19456474e-05,
        8.09388533e-05, 8.99320592e-05],
       [8.99320592e-06, 1.79864118e-05, 2.69796178e-05, 3.59728237e-05,
   

In [111]:
plat

array([[9.89252651e-05, 9.89252651e-05, 9.89252651e-05, 9.89252651e-05,
        9.89252651e-05, 9.89252651e-05, 9.89252651e-05, 9.89252651e-05,
        9.89252651e-05, 9.89252651e-05],
       [1.07918471e-04, 1.07918471e-04, 1.07918471e-04, 1.07918471e-04,
        1.07918471e-04, 1.07918471e-04, 1.07918471e-04, 1.07918471e-04,
        1.07918471e-04, 1.07918471e-04],
       [1.16911677e-04, 1.16911677e-04, 1.16911677e-04, 1.16911677e-04,
        1.16911677e-04, 1.16911677e-04, 1.16911677e-04, 1.16911677e-04,
        1.16911677e-04, 1.16911677e-04],
       [1.25904883e-04, 1.25904883e-04, 1.25904883e-04, 1.25904883e-04,
        1.25904883e-04, 1.25904883e-04, 1.25904883e-04, 1.25904883e-04,
        1.25904883e-04, 1.25904883e-04],
       [1.34898089e-04, 1.34898089e-04, 1.34898089e-04, 1.34898089e-04,
        1.34898089e-04, 1.34898089e-04, 1.34898089e-04, 1.34898089e-04,
        1.34898089e-04, 1.34898089e-04],
       [1.43891295e-04, 1.43891295e-04, 1.43891295e-04, 1.43891295e-04,
   